#!/bin/bash



updatelog=/var/log/updater.log
errorlog=/var/log/updatererrors.log
distupdaterlog=/var/log/distupdater.log
disterrorlog=/var/log/distupdatererror.log
osrelease=/etc/os-release

if grep -q "arch" $osrelease
then
	echo "arch found"
	sudo pacman -Syu
	exit 0
else
	exit 1
	echo "arch not found"
fi
if grep -q "ubuntu" $osrelease
then
	echo "ubuntu found" 
	sudo apt update 1>$updatelog 2>$errorlog
	sudo apt dist-upgrade 1>$distupdaterlog 2>$distupdatererror 
else
	exit 1
	echo "ubuntu not found"
fi
if grep -q "fedora" $osrelease
then
	echo "fedora found"
	sudo dnf update -y 1> $updatelog 2> $errorlog
	exit 1
else
	echo "fedora not found"
	exit 0
fi
